version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - proxy
    environment:
      - REACT_APP_WEBSOCKET_URL=ws://localhost:8080

  proxy:
    build: ./websocket-proxy
    ports:
      - "8080:8080"
    environment:
      - WS_PORT=8080
      - TCP_HOST=localhost
      - TCP_PORT=9000

  # Optional: TCP echo server for testing
  echo-server:
    image: alpine:latest
    command: sh -c "apk add --no-cache netcat-openbsd && nc -l -p 9000"
    ports:
      - "9000:9000"

